# Generated by Django 3.1.5 on 2021-12-20 01:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heading1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Heading',
                'verbose_name_plural': 'Headings',
            },
        ),
        migrations.CreateModel(
            name='Heading2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.heading1', verbose_name='Parent heading')),
            ],
            options={
                'verbose_name': 'Second-level heading',
                'verbose_name_plural': 'Second-level headings',
            },
        ),
        migrations.CreateModel(
            name='Heading3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.heading2', verbose_name='Parent heading')),
            ],
            options={
                'verbose_name': 'Third-level heading',
                'verbose_name_plural': 'Third-level headings',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Textfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('heading_level', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_table', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('key', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('parent_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.textfile')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('custom_name', models.BooleanField(default=True)),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Heading4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.heading3', verbose_name='Parent heading')),
            ],
            options={
                'verbose_name': 'Fourth-level heading',
                'verbose_name_plural': 'Fourth-level headings',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.page', verbose_name='Page'),
        ),
    ]
