# Generated by Django 3.1.5 on 2021-12-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211220_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
