# Generated by Django 3.0.5 on 2020-05-03 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200503_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='textfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
