# Generated by Django 3.0.5 on 2020-05-03 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200503_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='key',
            field=models.CharField(default=uuid.uuid1, max_length=64),
        ),
    ]
