# Generated by Django 3.1.5 on 2021-12-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_table_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading2',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='heading3',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='heading4',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
