# Generated by Django 3.1.5 on 2021-12-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211220_0428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
