# Generated by Django 3.0.5 on 2020-05-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_textfile_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='date',
            new_name='date_added',
        ),
    ]
