# Generated by Django 3.1.5 on 2021-12-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
