# Generated by Django 3.0.5 on 2020-05-03 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200503_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
