# Generated by Django 3.0.5 on 2020-05-04 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200503_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='parent_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Textfile'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
    ]
