# Generated by Django 3.1.5 on 2021-12-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chapter_is_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading1',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
