# Generated by Django 3.0.5 on 2020-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200504_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
