# Generated by Django 3.1.5 on 2021-12-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211221_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading2',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heading3',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heading4',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
