# Generated by Django 3.0.5 on 2020-05-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200504_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='parent_page',
            new_name='child_page',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='category',
        ),
        migrations.AddField(
            model_name='textfile',
            name='heading_level',
            field=models.IntegerField(default=1),
        ),
    ]
