# Generated by Django 3.1.5 on 2021-12-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211221_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heading1',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heading2',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heading3',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heading4',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
