# Generated by Django 3.1.5 on 2022-02-12 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211222_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='table_html',
        ),
        migrations.RemoveField(
            model_name='heading1',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='heading2',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='heading3',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='heading4',
            name='is_html',
        ),
        migrations.CreateModel(
            name='ChapterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('html', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app.chapter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
