# Generated by Django 3.0.5 on 2020-05-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200505_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='child_page',
            new_name='parent_page',
        ),
    ]
