# Generated by Django 3.1.5 on 2021-12-22 03:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211222_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='table_html',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
