# Generated by Django 3.1.5 on 2022-02-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220212_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading4Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('html', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app.heading4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heading3Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('html', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app.heading3')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heading2Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('html', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app.heading2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heading1Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('html', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app.heading1')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
