# Generated by Django 3.1.5 on 2021-12-22 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211222_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='table_html',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.table'),
        ),
    ]
