# Generated by Django 3.1.5 on 2021-12-22 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211222_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='table_html',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AddField(
            model_name='chaptertable',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chapter'),
        ),
    ]
