# Generated by Django 3.1.5 on 2021-06-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200506_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='is_table',
            field=models.BooleanField(default=False),
        ),
    ]
