# Generated by Django 3.1.5 on 2022-02-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_heading1table_heading2table_heading3table_heading4table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading1',
            name='table_html',
        ),
        migrations.RemoveField(
            model_name='heading2',
            name='table_html',
        ),
        migrations.RemoveField(
            model_name='heading3',
            name='table_html',
        ),
        migrations.RemoveField(
            model_name='heading4',
            name='table_html',
        ),
    ]
