# Generated by Django 3.1.5 on 2021-06-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_textfile_is_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
