# Generated by Django 3.1.5 on 2021-12-22 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211222_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptertable',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app.chapter'),
        ),
    ]
