# Generated by Django 3.1.5 on 2021-12-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211222_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='heading1',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='heading2',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='heading3',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='heading4',
            name='is_html',
        ),
    ]
