# Generated by Django 3.1.5 on 2022-02-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211225_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptertable',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
