# Generated by Django 3.1.5 on 2021-08-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0016_auto_20210825_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='heading1',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='heading2',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.heading1', verbose_name='Parent heading'),
        ),
        migrations.AlterField(
            model_name='heading3',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.heading2', verbose_name='Parent heading'),
        ),
        migrations.AlterField(
            model_name='heading4',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.heading3', verbose_name='Parent heading'),
        ),
        migrations.AlterField(
            model_name='table',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='contenttypes.contenttype'),
        ),
    ]
