# Generated by Django 3.1.5 on 2022-12-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20221227_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
