# Generated by Django 3.1.5 on 2023-01-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20221231_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
